spot_numbers: # List of spot numbers to be processed 
  - 1
  - 6
  - 61
  - 66  

run_id: # Run identifier for the run
  - 18
  - 20
  - 21
  - 22
  - 143

row_numbers: # Row number(s) for filtering in case 3
  - 1
  - 2
  # - 3
  # - 4

cassette_numbers: # Cassette number(s) for filtering in case 3
  - "Cassette 01"