spot_numbers: # List of spot numbers to be processed 
  - 1
  - 6
  - 61
  - 66  

run_id: # Run identifier for the run
  - 147
  - 148
  - 149
  - 150
  - 151
  - 152
  - 153
  - 154
  - 155
  - 156
  - 157
  - 158
  - 159
  - 160
  - 161
  

row_numbers: # Row number(s) for filtering in case 3
  - 1
  - 2
  # - 3
  # - 4

cassette_numbers: # Cassette number(s) for filtering in case 3
  - "Cassette 01"